dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  # the ignorde-modules=tensorflow is due to a bug using pyling in combination with tensorflow > 1.13
  - pylint agent.py --ignored-modules=tensorflow.keras
  - pylint poker_game.py
  - pylint play.py
  - pylint train.py
  - pylint self_play_analysis.py --ignored-modules=scipy --ignored-modules=matplotlib.pyplot
  - pylint self_play_between_versions.py --ignored-modules=scipy --ignored-modules=matplotlib.pyplot
  - pylint test_file.py
